name: Node CI

on:
  pull_request:
  push:
    branches: 
      - develop
      - development
      - master
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: action-yarn
      uses: comchangs/action-yarn@v0.1-beta
      with:
        args: "yarn install; yarn run build"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: install
        # Directory containing files to upload
        path: install
